"""arXiv's own LaTeXML-rendered HTML — the best source we can get for a paper.

Since December 2023 arXiv publishes an HTML rendering of most submissions,
generated by LaTeXML from the author's LaTeX. Every formula in it carries the
original TeX **twice**: once in the ``alttext`` attribute of the ``<math>``
element and once in ``<annotation encoding="application/x-tex">``. Measured on
a real 2026 hep-th paper: 767 ``<math>`` elements, 767 ``alttext``, 767
annotations — a perfect one-to-one-to-one.

That makes this route categorically different from every other one. It is not
recognition. Nothing is being read off a rendered page and guessed at; the TeX
was written down and we are reading it back. It also sidesteps three failure
modes of converting the e-print tarball ourselves, all three of which were
measured on real submissions:

  * picking the wrong main .tex out of a bundle that ships several
  * multi-file submissions stitched together with \\input
  * pandoc dying on old plain-TeX primitives (``\\vskip 0.3truein`` killed
    cond-mat/0001002 outright, producing nothing)

and it does not silently lose figures the way the tarball route can (arXiv
2401.00506: six referenced, zero survived, run reported success).

What it does lose is the *layout* around each formula — LaTeXML sets
equations as tables and pandoc writes those back as Markdown tables — and the
author's own macros, which the TeX keeps verbatim. `latexml_math` repairs the
first and `tex_macros` recovers the second from the e-print, which is why this
route fetches the source too: not to convert it, only to read its definitions.

Coverage, measured: 8/10 recent papers on the native endpoint; 14/15 on ar5iv
for the pre-2023 range that dominates an older physics library. Papers that
miss on both are a real outcome, not an era artifact — fall through to the
tarball.
"""

from __future__ import annotations

import html as html_module
import os
import re
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError
from urllib.parse import urljoin

import yaml

from magi.core.arxiv_id import abs_url, normalize_arxiv_id
from magi.core.config_loader import load_config
from magi.core.http import http_get
from magi.core.tools import find_pandoc
from magi.core.wiki_common import atomic_write, slugify
from magi.ingest import image_refs
from magi.ingest.convert_result import ConversionResult

NATIVE_URL = "https://arxiv.org/html/{id}"
AR5IV_URL = "https://ar5iv.labs.arxiv.org/html/{id}"

# arXiv answers a missing /html paper with its standard error page. Measured at
# exactly 7899 bytes; real renderings in the same sample ran 150 KB to 1.3 MB.
# The size alone is not the test — see _looks_like_a_paper — but it is a useful
# tripwire if that page ever grows.
_ERROR_PAGE_CEILING = 20_000

_MATH_ALTTEXT_RE = re.compile(r'<math[^>]*\balttext="([^"]*)"', re.IGNORECASE)
_ANNOTATION_RE = re.compile(
    r'<annotation encoding="application/x-tex">(.*?)</annotation>',
    re.IGNORECASE | re.DOTALL)
_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)


class FetchResult:
    """One attempt at one endpoint."""

    def __init__(self, ok: bool, *, body: bytes = b"", url: str = "",
                 endpoint: str = "", reason: str = ""):
        self.ok = ok
        self.body = body
        self.url = url
        self.endpoint = endpoint
        self.reason = reason


def _looks_like_a_paper(body: bytes, requested_url: str, final_url: str) -> tuple[bool, str]:
    """Did we actually get a rendering, or something that merely returned 200?

    Three ways this lies, all observed:

    * **ar5iv redirects to the abstract page** when it has no rendering. The
      status is 200 and the body is a real page — of the abstract. Scoring on
      the status code alone counts that as coverage.
    * **arXiv's /html 404 body** is a full HTML error page, not an empty one.
    * A rendering with no ``alttext`` anywhere is not useful to us even if it
      is a page about the right paper.
    """
    if "/abs/" in final_url and "/html/" in requested_url:
        return False, "redirected to the abstract page (no rendering exists)"
    if len(body) < _ERROR_PAGE_CEILING:
        return False, f"body is only {len(body)} bytes — an error page, not a paper"
    text = body.decode("utf-8", errors="replace")
    if not _MATH_ALTTEXT_RE.search(text) and "alttext=" not in text:
        return False, "rendering carries no alttext — the TeX is not recoverable from it"
    return True, ""


def fetch(arxiv_id: str, *, timeout: int = 60) -> FetchResult:
    """Native endpoint first, ar5iv second. Both are rate-limited to 15 s/request
    by the shared Throttle (arXiv's robots.txt sets Crawl-delay: 15 for /html)."""
    arxiv_id = normalize_arxiv_id(arxiv_id) or arxiv_id
    attempts = (("arxiv", NATIVE_URL.format(id=arxiv_id)),
                ("ar5iv", AR5IV_URL.format(id=arxiv_id)))
    last_reason = "no endpoint returned a rendering"
    for endpoint, url in attempts:
        try:
            body, _ctype, final_url = http_get(url, timeout=timeout)
        except HTTPError as exc:
            last_reason = f"{endpoint}: HTTP {exc.code}"
            continue
        except Exception as exc:  # noqa: BLE001 — urllib raises a family
            last_reason = f"{endpoint}: {exc}"
            continue
        ok, why = _looks_like_a_paper(body, url, final_url)
        if ok:
            return FetchResult(True, body=body, url=final_url, endpoint=endpoint)
        last_reason = f"{endpoint}: {why}"
    return FetchResult(False, reason=last_reason)


def extract_tex_formulas(page: str) -> list[str]:
    """Every formula's original TeX, in document order.

    Prefers ``<annotation>`` over ``alttext``: the attribute is HTML-escaped
    (``&lt;``, ``&amp;``) and the element is not, so the element needs no
    unescaping round-trip that could itself mangle a ``\\&`` or a ``<``.
    """
    annotations = _ANNOTATION_RE.findall(page)
    if annotations:
        return [html_module.unescape(a).strip() for a in annotations]
    return [html_module.unescape(a).strip() for a in _MATH_ALTTEXT_RE.findall(page)]


#: The document title as ar5iv marks it. Preferred over `<title>` because it
#: is the paper's title by construction, where `<title>` is whatever the
#: converter had to hand — on a document with no title element that turns out
#: to be the first heading.
_DOC_TITLE_RE = re.compile(
    r"<h1[^>]*class=\"[^\"]*ltx_title_document[^\"]*\"[^>]*>(.*?)</h1>",
    re.IGNORECASE | re.DOTALL)

#: What a section heading looks like when it has been mistaken for a title.
#: Deliberately narrow: a false positive here costs a real title, and the
#: fallback is the arXiv id, which is honest but useless to read.
_SECTION_WORDS_RE = re.compile(
    r"^(abstract|introduction|zusammenfassung|contents|references|summary"
    r"|conclusions?|appendix|acknowledg(e)?ments)$", re.IGNORECASE)

#: A leading section number, with or without the space the heading dropped:
#: the observed value was "1Introduction", not "1 Introduction".
_SECTION_NUMBER_RE = re.compile(r"^\d+(\.\d+)*\s*")


def _is_a_heading(title: str) -> bool:
    """Is this a section heading wearing a title's place?

    The number is stripped before the word is judged so that "1Introduction"
    and "2.1 Introduction" both reduce to "Introduction". Matching on the word
    afterwards rather than on the number keeps a real title like "2D materials
    and their defects" — strip its number and "D materials and their defects"
    is not a section word.
    """
    return bool(_SECTION_WORDS_RE.match(_SECTION_NUMBER_RE.sub("", title).strip()))


def _text_of(markup: str) -> str:
    """Element text with tags turned into spaces, not deleted.

    Deleting them welded words together — `invariants of<span>Pauli` became
    `ofPauli` — which reads as a typo in the source rather than as damage the
    converter did.
    """
    return html_module.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", markup))).strip()


def page_title(page: str) -> str | None:
    """The paper's title, or None rather than a section heading.

    Measured on live pages: 2204.06023 came back as "Homological invariants
    ofPauli stabilizer codes", 1806.08679 as "Abstract", 2406.12962 as
    "1Introduction". The first is markup damage; the other two are documents
    that carry no title element, where `<title>` holds the first heading.

    Returning None sends the caller to the arXiv id, which is plainly not a
    title and gets noticed. A plausible wrong title does not.
    """
    m = _DOC_TITLE_RE.search(page)
    if m:
        title = _text_of(m.group(1))
        if title:
            return title

    m = _TITLE_RE.search(page)
    if not m:
        return None
    title = _text_of(m.group(1))
    # arXiv prefixes the id: "[2608.20333] Real Title Here".
    title = re.sub(r"^\[[^\]]+\]\s*", "", title)
    if not title or _is_a_heading(title):
        return None
    return title


def figure_slug(arxiv_id: str) -> str:
    """The prefix this paper's figure files carry.

    Keeps the id readable in a filename — ``cond-mat/0001002`` becomes
    ``cond-mat-0001002`` rather than losing the separator entirely — while
    staying unique, which is the only property that actually matters here.
    """
    return arxiv_id.replace("/", "-")


_SITE_ROOT = "https://arxiv.org"


def _absolutize_site_chrome(md: str) -> str:
    """Give arXiv's own furniture a URL that means what it says.

    Pandoc pulls the whole page in, so the output carries arXiv's funder logos
    and UI glyphs alongside the paper's figures, as site-absolute paths like
    ``/static/base/1.0.1/images/icons/smileybones-small.svg``. Those are not
    this paper's figures and must not be downloaded into its images/ directory
    — but left as-is they are references to a filesystem root that has no such
    file, which is to say dead links dressed as working ones.

    Pointing them at arxiv.org costs nothing, makes each reference true, and
    keeps the portability gate quiet about the one thing in an arXiv document
    that is legitimately not ours. Deleting them would be the other defensible
    answer; this one does not have to decide what is furniture and what is not.
    """
    def resolve(target: str):
        return _SITE_ROOT + target if target.startswith("/") else None

    out, _ = image_refs.rewrite(md, resolve, prefix="")
    return out


def _rewrite_image_paths(md: str, arxiv_id: str) -> tuple[str, int, dict[str, str]]:
    """Point figure references at ``images/<id>-<name>`` and report the originals.

    arXiv serves figures as relative paths under ``{id}v{n}/``, and the names
    inside are the author's: ``fig1.png``, ``setup.pdf``, ``x.png``. Those
    names are unique within one submission and not remotely unique across a
    library. Two papers each shipping a ``fig1.png`` used to land on the same
    ``raw/papers/images/fig1.png`` at commit, where the second copy silently
    won and one of the two papers then displayed the other's figure — no error,
    no missing file, just the wrong picture. So the id goes into the filename,
    which is what the tex and MinerU routes already do.

    Returns ``{original relative target: local filename}`` rather than a bare
    list, because the caller has to fetch these and the document and the
    directory must agree on the name. Handing back the mapping is what makes
    disagreeing impossible; two independent derivations of "the same" name is
    how the two drift apart.
    """
    # Settle arXiv's own furniture first, so what remains unresolved is either
    # this paper's figure or something we have no business touching.
    md = _absolutize_site_chrome(md)

    # A real figure is served relative to the page, under {id}v{n}/ — that is
    # what separates this paper's images from everything else on the page.
    figure_re = re.compile(rf"^{re.escape(arxiv_id)}v\d+/", re.IGNORECASE)
    slug = figure_slug(arxiv_id)

    def resolve(target: str):
        if not figure_re.match(target):
            return None
        return image_refs.namespaced(slug, target)

    # Count occurrences, not distinct files: a paper that shows the same figure
    # twice has two references, and one file to fetch.
    before = image_refs.iter_targets(md)
    md, mapping = image_refs.rewrite(md, resolve)
    n = sum(1 for target in before if target in mapping)
    return md, n, mapping


def download_figures(mapping, page_url: str, images_dir) -> tuple[int, list[str]]:
    """Fetch each relative figure next to the markdown. Returns (ok, failures).

    Takes the mapping `_rewrite_image_paths` produced, so each file is saved
    under exactly the name the document now references.

    Throttled like any other arxiv.org request: the figures live under ``/html``
    too, and robots.txt sets ``Crawl-delay: 15`` for that whole path. That makes
    a five-figure paper cost about a minute, which is the honest price of not
    hammering someone else's server. Pass ``--no-figures`` when you would rather
    have the text now.
    """
    images_dir = Path(images_dir)
    ok = 0
    failures: list[str] = []
    for target, name in mapping.items():
        # Plain urljoin: the page URL ends in the paper id, which is a resource
        # not a directory, so `2608.20333v1/torus.png` resolves against /html/.
        # Appending a slash first would treat the id as a directory and produce
        # /html/2608.20333/2608.20333v1/torus.png.
        url = urljoin(page_url, target)
        try:
            body, _ctype, _final = http_get(url, timeout=60)
        except Exception as exc:  # noqa: BLE001
            failures.append(f"{name} ({exc})")
            continue
        images_dir.mkdir(parents=True, exist_ok=True)
        (images_dir / name).write_bytes(body)
        ok += 1
    return ok, failures


def _regroup_align_tables(md: str) -> tuple[str, int]:
    """Restore ``\\begin{aligned}`` around what LaTeXML split into table rows.

    LaTeXML wraps an ``align`` environment in a table with one ``<math>`` per
    row. Pandoc renders that as a grid table: the row order and the shared
    equation number survive, but the alignment is no longer expressed as LaTeX,
    so MathJax in Obsidian shows a table of separate equations instead of one
    aligned block. Measured on arXiv 2401.00506.

    Consecutive display-math blocks that carry ``&`` anchors are the signature
    of exactly this, so fold them back into one aligned environment.
    """
    block = re.compile(r"(?:^\$\$\n(.+?)\n\$\$\n?){2,}", re.MULTILINE | re.DOTALL)
    runs = 0

    def repl(m):
        nonlocal runs
        chunk = m.group(0)
        rows = re.findall(r"^\$\$\n(.+?)\n\$\$", chunk, re.MULTILINE | re.DOTALL)
        if len(rows) < 2 or not any("&" in r for r in rows):
            return chunk
        runs += 1
        body = " \\\\\n".join(r.strip() for r in rows)
        return "$$\n\\begin{aligned}\n" + body + "\n\\end{aligned}\n$$\n"

    return block.sub(repl, md), runs


def convert(arxiv_id: str, output_dir, *, doc_type: str | None = None,
            fetch_figures: bool = True, fetch_source: bool = True) -> ConversionResult:
    """Fetch a paper's arXiv HTML and write it into ``output_dir`` as Markdown.

    *fetch_source* also reads the paper's e-print for the author's macro
    definitions — one more request to arXiv, nothing converted from it.
    """
    from magi.ingest import latexml_math, tex_macros
    from magi.kb.validate_math_latex import MACROS_SUFFIX

    ident = normalize_arxiv_id(arxiv_id)
    if not ident:
        return ConversionResult.failed(f"'{arxiv_id}' is not an arXiv identifier.")

    output_dir = os.path.abspath(str(output_dir))
    os.makedirs(output_dir, exist_ok=True)

    print(f"Fetching arXiv HTML for {ident}...", flush=True)
    got = fetch(ident)
    if not got.ok:
        print(f"No arXiv HTML rendering available: {got.reason}")
        return ConversionResult.failed(
            f"No arXiv HTML rendering for {ident}: {got.reason}")
    print(f"Got a rendering from {got.endpoint} ({len(got.body)} bytes)", flush=True)

    page = got.body.decode("utf-8", errors="replace")
    formulas = extract_tex_formulas(page)
    title = page_title(page) or ident

    pandoc = find_pandoc()
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "page.html")
        Path(src).write_bytes(got.body)
        out_md = os.path.join(tmp, "page.md")
        cmd = [pandoc, src, "-f", "html", "-t", "markdown", "-o", out_md]
        print(f"Running Pandoc: {' '.join(cmd)}")
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            print("Pandoc conversion failed:")
            print(proc.stderr)
            return ConversionResult.failed(
                "Pandoc failed to convert the arXiv HTML.", proc.stderr.strip())
        md_content = Path(out_md).read_text(encoding="utf-8", errors="replace")

    md_content, n_figs, fig_map = _rewrite_image_paths(md_content, ident)

    macros, math_packages, source_why = {}, [], None
    if fetch_source:
        print("Fetching the LaTeX source for the author's macro definitions...", flush=True)
        macros, math_packages, source_why = tex_macros.from_eprint(ident)
    md_content, repairs, left = latexml_math.normalize(md_content, macros=macros)
    md_content, n_regrouped = _regroup_align_tables(md_content)

    images_dir = os.path.join(output_dir, "images")
    n_figs_ok, fig_failures = 0, []
    if fetch_figures and fig_map:
        print(f"Fetching {len(fig_map)} figure(s)...", flush=True)
        n_figs_ok, fig_failures = download_figures(fig_map, got.url, images_dir)
        print(f"Figures: {n_figs_ok} saved into images/, {len(fig_failures)} failed")

    if doc_type not in ("papers", "articles", "notes", "repos"):
        doc_type = os.path.basename(os.path.normpath(output_dir))
        if doc_type not in ("papers", "articles", "notes", "repos"):
            doc_type = "papers"

    today = datetime.now().strftime("%Y-%m-%d")
    fm = {
        "title": title,
        "source": got.url,
        "type": doc_type,
        "ingested": today,
        "tags": [],
        "summary": f"Converted from arXiv HTML ({got.endpoint}, LaTeXML).",
        "arxiv_id": ident,
        "arxiv_url": abs_url(ident),
    }
    frontmatter = ("---\n" + yaml.safe_dump(fm, allow_unicode=True, sort_keys=False,
                                            default_flow_style=False) + "---\n")

    output_path = os.path.join(output_dir, f"{today}-{slugify(title)}.md")
    atomic_write(output_path, frontmatter + "\n" + md_content, encoding="utf-8")
    print(f"Successfully converted and saved to {output_path}")

    # What `magi math check` needs to compile this paper that is not in the
    # document itself: definitions no formula could have expanded in place,
    # and the maths packages the paper loads.
    leftover = tex_macros.used_in_math(md_content, macros)
    sidecar = None
    if leftover or math_packages:
        sidecar = Path(output_path).with_name(Path(output_path).stem + MACROS_SUFFIX)
        atomic_write(sidecar, tex_macros.sidecar_text(
            leftover, math_packages, origin=f"the arXiv:{ident} e-print"), encoding="utf-8")

    outcome = ConversionResult(
        success=True,
        markdown_path=str(output_path),
        images_dir=images_dir,
    )
    outcome.flag("route-arxiv-html",
                 f"{len(formulas)} formula(s) carried verbatim TeX from {got.endpoint}",
                 severity="info")
    # Line numbers in the document as written, frontmatter included.
    offset = frontmatter.count("\n") + 1
    if repairs:
        outcome.flag("math-layout-repaired",
                     f"{len(repairs)} repair(s) to what LaTeXML and pandoc did to the "
                     f"formulas: {latexml_math.describe(repairs)}", severity="info")
    if left:
        first = min(item.line for item in left) + offset
        outcome.flag("math-layout-left",
                     f"{len(left)} formula layout(s) could not be repaired mechanically "
                     f"({latexml_math.describe(left)}; first at line {first}) — each was "
                     "left exactly as converted; compare with the PDF")
    if fetch_source and source_why:
        outcome.flag("author-macros-unavailable",
                     f"{source_why}; the author's own macros stay as written",
                     severity="info")
    elif sidecar is not None:
        outcome.flag("author-macros-kept",
                     f"{len(leftover)} author definition(s) and {len(math_packages)} maths "
                     f"package(s) recorded in {sidecar.name} for `magi math check`",
                     severity="info")
    if n_regrouped:
        outcome.flag("align-regrouped",
                     f"{n_regrouped} multi-line equation group(s) restored to "
                     "\\begin{aligned}; LaTeXML had split them into table rows",
                     severity="info")
    if fig_failures:
        outcome.flag("figure-download-failed",
                     f"{len(fig_failures)} figure(s) could not be fetched and will "
                     f"be broken links: {', '.join(fig_failures[:5])}")
    elif n_figs and not fetch_figures:
        outcome.flag("figures-skipped",
                     f"{n_figs} figure reference(s) point at images/ but figure "
                     "fetching was disabled — these are broken links")
    elif n_figs_ok:
        outcome.flag("figures-saved", f"{n_figs_ok} figure(s) saved into images/",
                     severity="info")
    return outcome


def main(argv=None):
    import argparse

    parser = argparse.ArgumentParser(
        prog="magi ingest arxiv-html",
        description="Fetch arXiv's LaTeXML HTML for a paper and convert it to Markdown.")
    parser.add_argument("arxiv_id", help="arXiv identifier, e.g. 2608.16520 or cond-mat/0506438")
    parser.add_argument("-o", "--output_dir", required=True,
                        help="Output directory for the raw Markdown file.")
    parser.add_argument("--no-figures", action="store_true",
                        help="Skip figure downloads. Faster, but the figure links "
                             "in the output will be broken (arXiv asks for 15s "
                             "between requests, so figures dominate the wall time).")
    parser.add_argument("--no-source", action="store_true",
                        help="Do not read the paper's LaTeX source for the author's "
                             "macros (saves one request; macros then stay as written).")
    args = parser.parse_args(argv)

    result = convert(args.arxiv_id, args.output_dir,
                     fetch_figures=not args.no_figures,
                     fetch_source=not args.no_source)
    for finding in result.findings:
        print(f"  {finding}")
    return 0 if result.success else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
